#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"
printenv

echo "SOURCE_BRANCH -> $SOURCE_BRANCH"
echo "executed command -> docker build --build-arg REPOSITORY=\"$REPOSITORY\" --build-arg BRANCH=\"$SOURCE_BRANCH\" --build-arg ADDITIONAL_PACKAGES=\"$ADDITIONAL_PACKAGES\" -t $IMAGE_NAME ."

docker build \
  --build-arg REPOSITORY="$REPOSITORY" \
  --build-arg BRANCH="$SOURCE_BRANCH" \
  --build-arg ADDITIONAL_PACKAGES="$ADDITIONAL_PACKAGES" \
  -t "$IMAGE_NAME" .

echo "------ HOOK END - BUILD -------"
